### ISSUE TITLE
Feature: Add Point manually 

### ISSUE THREAD

**Issue by KuLi** [bvanhoekelen/performance#5]
It would be nice to add points manually. This way it would be possible to keep the measurement running when hitting another point. For example whole site duration or multiple tasks. Or you could finish a point by its label. For example

```php
Performance::point("site:start");
//run code
Performance::point("cache");
//run code
Performance::finish(); // finish cache point
//run code
Performance::finish(); // finish site:start

Or 

Performance::finish("cache");
Performance::finish("site:start");
```

**Comment by bvanhoekelen** [comment]
It's a good idea. I will add this functionality in version 2.3.1. Note that if you use this multiple point function the measurement are less accurate. This is because you will measure your task and also the performance tool.

For more info over the multiple point function, see example 12 in de example folder on git.

**Comment by bvanhoekelen** [comment]
Code and documentation is updated. See https://github.com/bvanhoekelen/performance/wiki/Multiple-points and https://github.com/bvanhoekelen/performance/releases/tag/v2.3.1
